name: github-token
description:
inputs:
  github_token:
    description: GitHub Access Token
    required: false
  github_app_id:
    description: GitHub App ID
    required: false
  github_app_private_key:
    description: GitHub App Private Key
    required: false
  default_github_token:
    description: GitHub Access Token
    required: false
outputs:
  token:
    description: GitHub Access Token
    value: ${{steps.output_token.outputs.token}}
  token_type:
    description: github_token, github_app_token, default_github_token, empty
    value: ${{steps.output_token.outputs.token_type}}
runs:
  using: composite
  steps:
    - id: check
      shell: bash
      env:
        TOKEN: ${{inputs.github_token}}
        APP_ID: ${{inputs.github_app_id}}
        APP_PRIVATE_KEY: ${{inputs.github_app_private_key}}
      run: |
        set -eu
        if [ -n "$TOKEN" ]; then
          echo "token=true" >> "$GITHUB_OUTPUT"
        fi
        if [ -n "$APP_ID" ]; then
          echo "app_id=true" >> "$GITHUB_OUTPUT"
        fi
        if [ -n "$APP_PRIVATE_KEY" ]; then
          echo "app_private_key=true" >> "$GITHUB_OUTPUT"
        fi

    - id: generate_token
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
      with:
        app_id: ${{inputs.github_app_id}}
        private_key: ${{inputs.github_app_private_key}}
      if: steps.check.outputs.app_id == 'true'

    - id: output_token
      shell: bash
      env:
        GH_TOKEN: ${{github.token}}
        TOKEN: ${{inputs.github_token}}
        DEFAULT_TOKEN: ${{inputs.default_github_token}}
        APP_TOKEN: ${{steps.generate_token.outputs.token}}
      run: |
        set -eu
        token="$DEFAULT_TOKEN"
        token_type=default_github_token
        if [ -n "$TOKEN" ]; then
          token="$TOKEN"
          token_type=github_token
        elif [ -n "$APP_TOKEN" ]; then
          token="$APP_TOKEN"
          token_type=github_app_token
        fi
        echo "token=$token" >> "$GITHUB_OUTPUT"
        if [ -z "$token" ]; then
          token_type=empty
        fi
        echo "token_type=$token_type" >> "$GITHUB_OUTPUT"
